2019-07-13 14:51:37,434 : kivy : Factory: 194 symbols loaded
2019-07-13 14:51:38,006 : kivy : Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
2019-07-13 14:51:38,409 : kivy : VideoGstplayer: Using Gstreamer 1.10.2.0
2019-07-13 14:51:38,410 : kivy : Video: Provider: gstplayer
2019-07-13 14:51:38,680 : kivy : Loading MPF-MC controller
2019-07-13 14:51:38,680 : mpfmc : Mission Pinball Framework Media Controller v0.50.8
2019-07-13 14:51:38,681 : mpfmc : Mission Pinball Framework Game Engine v0.50.13
2019-07-13 14:51:38,681 : mpfmc : Machine path: C:\OPP\MPF\MPFTest
2019-07-13 14:51:38,682 : ConfigProcessor : Cache file not found: C:\Users\Dorus\AppData\Local\Temp\79086b7abd0dd55f074ebe0828a99f51.mpf_cache
2019-07-13 14:51:39,147 : ConfigProcessor : Loading config from file c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml.
2019-07-13 14:51:39,207 : ConfigProcessor : Loading config: c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpfmc\mcconfig.yaml
2019-07-13 14:51:39,208 : ConfigProcessor : Loading config from file C:\OPP\MPF\MPFTest\config\config.
2019-07-13 14:51:39,208 : kivy : Error found in file C:\OPP\MPF\MPFTest\config\config.yaml: Version mismatch. Expected: #config_version=5 Actual: #config_version=3 Files: C:\OPP\MPF\MPFTest\config\config.yaml
Traceback (most recent call last):
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 193, in load
    expected_version_str, version_str, filename))
AssertionError: Version mismatch. Expected: #config_version=5 Actual: #config_version=3 Files: C:\OPP\MPF\MPFTest\config\config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpfmc\commands\mc.py", line 189, in __init__
    thread_stopper=thread_stopper).run()
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 95, in __init__
    self.machine_config = self._load_config()
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpfmc\core\mc.py", line 224, in _load_config
    mpf_config = self.mpf_config_processor.load_config_files_with_cache(files, "machine", True)
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\core\file_manager.py", line 154, in load
    return interface.load(file, verify_version, halt_on_error)
  File "c:\users\dorus\appdata\local\programs\python\python36\lib\site-packages\mpf\file_interfaces\yaml_interface.py", line 208, in load
    raise ValueError(msg)
ValueError: Error found in file C:\OPP\MPF\MPFTest\config\config.yaml: Version mismatch. Expected: #config_version=5 Actual: #config_version=3 Files: C:\OPP\MPF\MPFTest\config\config.yaml
2019-07-13 14:51:39,235 : kivy : Stopping child threads... (0 remaining)
2019-07-13 14:51:39,236 : kivy : All child threads stopped.
